export default {
  FONTS: {
    Black: 'Inter_24pt-Black',
    BlackItalic: 'Inter_24pt-BlackItalic',
    bold: 'Inter_24pt-Bold',
    boldItalic: 'Inter_24pt-BoldItalic',
    ExtraBold: 'Inter_24pt-ExtraBold',
    ExtraBoldItalic: 'Inter_24pt-ExtraBoldItalic',
    Italic: 'Inter_24pt-Italic',
    Light: 'Inter_24pt-Light',
    LightItalic: 'Inter_24pt-LightItalic',
    Medium: 'Inter_24pt-Medium',
    MediumItalic: 'Inter_24pt-MediumItalic',
    Regular: 'Inter_24pt-Regular',
    SemiBold: 'Inter_24pt-SemiBold',
    SemiBoldItalic: 'Inter_24pt-SemiBoldItalic',
    Thin: 'Inter_24pt-Thin',
    ThinItalic: 'Inter_24pt-ThinItalic',
    ExtraLight: 'Inter_24pt-ExtraLight',
    ExtraLightItalic: 'Inter_24pt-ExtraLightItalic',
    PlayfairDisplaySCBlack: 'PlayfairDisplaySC-Black',
    PlayfairDisplaySCBlackItalic: 'PlayfairDisplaySC-BlackItalic',
    PlayfairDisplaySCBold: 'PlayfairDisplaySC-Bold',
    PlayfairDisplaySCBoldItalic: 'PlayfairDisplaySC-BoldItalic',
    PlayfairDisplaySCItalic: 'PlayfairDisplaySC-Italic',
    PlayfairDisplaySCRegular: 'PlayfairDisplaySC-Regular',
    PlayfairBlack: 'Playfair_144pt-Black',
    PlayfairBlackItalic: 'Playfair_144pt-BlackItalic',
    PlayfairBold: 'Playfair_144pt-Bold',
    PlayfairBoldItalic: 'Playfair_144pt-BoldItalic',
    PlayfairItalic: 'Playfair_144pt-Italic',
    PlayfairRegular: 'Playfair_144pt-Regular',
    PlayfairMedium: 'Playfair_144pt-Medium',
    PlayfairRegular: 'Playfair_144pt-Regular',
  },
};
